import "./globals.scss";
// import { Inter } from "next/font/google";
import Header from "../components/Header";
import Provider from "@/context/AuthContext";
import ToasterContext from "@/context/ToasterContext";

// const inter = Inter({ subsets: ["latin"] });

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body>
                <Provider>
                    <ToasterContext />
                    <Header />
                    <main>{children}</main>
                </Provider>
            </body>
        </html>
    );
}
